$(document).ready(function() {
var width = $(document).width();
var height = $(document).height();
var g = new Graph();
g.edgeFactory.template.style.directed = false;
g.addNode("1");
g.addNode("2");
g.addNode("3");
g.addNode("4");
g.addNode("5");
g.addNode("6");
g.addNode("7");
g.addNode("8");
g.addNode("9");
g.addNode("10");
g.addNode("11");
g.addNode("12");
g.addNode("13");
g.addNode("14");
g.addNode("15");
g.addNode("16");
g.addNode("17");
g.addNode("18");
g.addNode("19");
g.addNode("20");
g.addNode("21");
g.addNode("22");
g.addNode("23");
g.addNode("24");
g.addNode("25");
g.addNode("26");
g.addNode("27");
g.addNode("28");
g.addNode("29");
g.addNode("30");
g.addNode("31");
g.addNode("32");
g.addNode("33");
g.addNode("34");
g.addNode("35");
g.addNode("36");
g.addNode("37");
g.addNode("38");
g.addNode("39");
g.addNode("40");
g.addNode("41");
g.addNode("42");
g.addNode("43");
g.addNode("44");
g.addNode("45");
g.addNode("46");
g.addNode("47");
g.addNode("48");
g.addNode("49");
g.addEdge("1","3");
g.addEdge("1","3");
g.addEdge("1","3");
var layouter = new Graph.Layout.Ordered(g, topological_sort(g));
var renderer = new Graph.Renderer.Raphael('canvas', g, width, height);
});